### ISSUE TITLE
Rails 5.0.7 + CPK 9.0.8: undefined local variable or method `always_initialized' 

### ISSUE THREAD

**Issue by cmager** [composite-primary-keys/composite_primary_keys#437]
After update to Rails / Active Record 5.0.7 I get this error message for every AR model call:
That worked on rails 5.0.6 before. Any ideas or anyone having the same issues?

```
SomeModel.first
=> NameError: undefined local variable or method `always_initialized' for #<ActiveRecord::AttributeSet::Builder:0x007fcd3bd45c28>
from /Users/cmager/.rvm/gems/ruby-2.3.4@dev/gems/composite_primary_keys-9.0.8/lib/composite_primary_keys/attribute_set/builder.rb:10:in `build_from_database'
```

**Comment by mauroc** [comment]
I just installed rails 5.1.6 and [composite_primary_keys](https://github.com/composite-primary-keys/composite_primary_keys) 10.0.3, but still getting this error.

**Comment by cfis** [comment]
Yeah seems like #435.

**Comment by jkowens** [comment]
@cfis will there be a 9.0.x release with the latest patch?

**Comment by cfis** [comment]
I'm guessing the patch is similar to what was done in 5.1.x.
https://github.com/composite-primary-keys/composite_primary_keys/pull/448/files

I try to limit support to the last two versions, so 5.2.x and 5.1.x.  But if someone can take the time to see if that patch works on 5.0.x I'm happy to apply it.

Charlie

**Comment by cfis** [comment]
Closing - thanks jkowens!
