### PR TITLE
Apply patch to fix AR 5.0.7

### LINKED ISSUE #437: Rails 5.0.7 + CPK 9.0.8: undefined local variable or method `always_initialized'
After update to Rails / Active Record 5.0.7 I get this error message for every AR model call:
That worked on rails 5.0.6 before. Any ideas or anyone having the same issues?

```
SomeModel.first
=> NameError: undefined local variable or method `always_initialized' for #<ActiveRecord::AttributeSet::Builder:0x007fcd3bd45c28>
from /Users/cmager/.rvm/gems/ruby-2.3.4@dev/gems/composite_primary_keys-9.0.8/lib/composite_primary_keys/attribute_set/builder.rb:10:in `build_from_database'
```

### PR DESCRIPTION
**Pull request by jkowens**
Fixes #437.

### CODE REVIEW

**Comment by cfis** [comment]
Thanks!
